"""Debian resolution Layer — runtime dependency validation.

Every explicitly emitted runtime dependency must correspond to a real,
installable Debian package.  This module is the single enforcement point
that prevents upstream logical names (e.g. 'libefl') from leaking into
'debian/control'.

Design constraints
------------------
* No project-specific rules.  Detection is purely name-based via apt.
* Deterministic: the :class:`~deb.resolution.oracle.AptOracle` is the sole
  source of truth for package existence.
* ELF-dynamic deps are NOT passed here; they are already suppressed by the
  'elf-dynamic' provenance filter in 'debian_generator._non_elf_runtime_deps'
  and delegated to '${shlibs:Depends}'.  Only non-ELF inferred deps reach
  this layer.
* All validation functions accept an explicit 'oracle' parameter so that
  callers can supply a :class:`~deb.resolution.oracle.ChrootAptOracle` when
  building inside a clean Debian chroot.  Without an oracle the functions
  default to :class:`~deb.resolution.oracle.HostAptOracle`, which may be
  contaminated by non-Debian packages on the build host.

Public API
----------
'resolve_runtime_dependencies(deps, oracle)'
    Given a list of candidate runtime package names, return only those
    confirmed to exist in the oracle's apt database.  Unresolvable names
    are dropped with a logged warning.

'validate_extra_depends(extra_depends, generated_pkg_names, pkg_label, oracle)'
    Validate one package's 'extra_depends' list, preserving generated
    intra-package deps (sibling packages, lockstep version pins) and
    debhelper substitution variables, and verifying everything else via
    the oracle.

'validate_built_debs(deb_paths, generated_pkg_names, oracle)'
    Inspect every retained .deb and raise 'RuntimeError' if any Depends
    group is invalid according to the oracle.  Enrich failures with
    shlibs-repair diagnostics.

'check_apt_package(name, oracle)'
    Low-level: return True when *name* is a known apt candidate in *oracle*.
"""

from __future__ import annotations

import subprocess

from deb.resolution.oracle import AptOracle, HostAptOracle, make_oracle
from deb.resolution.shlibs_repair import repair_shlibs_deps
from deb.utils.log import error, info


# ---------------------------------------------------------------------------
# Low-level apt oracle helper
# ---------------------------------------------------------------------------

def check_apt_package(
    name: str,
    oracle: AptOracle | None = None,
) -> bool:
    """Return True when *name* is a real, apt-installable Debian package.

    Delegates to *oracle*.package_exists().  If *oracle* is 'None', a
    :class:`~deb.resolution.oracle.HostAptOracle` is used (with an implicit
    contamination warning emitted by :func:`~deb.resolution.oracle.make_oracle`).

    Args:
        name: A Debian package name, optionally with a version constraint.
        oracle: The apt oracle to query.  Pass 'None' only when no target
                environment is available (host-scoped fallback).

    Returns:
        True if the package has a real candidate version in the oracle's
        apt database.
    """
    if oracle is None:
        oracle = make_oracle(None)
    return oracle.package_exists(name)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _is_generated_dep(dep: str, generated_pkg_names: frozenset[str]) -> bool:
    """Return True for deps that are internally generated and need no apt check.

    Three categories are exempt from apt validation:

    1. Debhelper substitution variables — '${shlibs:Depends}',
       '${misc:Depends}', etc.  These are resolved at build time by
       debhelper and are always valid in 'debian/control'.

    2. Same-binary-version sibling deps — any dep of the form
       '<name> (= ${binary:Version})' where the bare name is one of the
       packages generated by this very run.  These are intra-package deps
       synthesised by 'synthesize_intra_deps' and 'dev_pkg_main_dep';
       they reference packages that do not exist in the apt database yet.

    3. Runtime-shlib sibling deps — when the runtime shlib package
       (e.g. '<app>-runtime') appears in 'generated_pkg_names' and the
       dep bare name matches it (with or without a version qualifier).  This
       is a subset of rule 2 but is covered by the same logic.
    """
    bare = dep.split("(")[0].strip()

    # 1. Debhelper substitution variable or empty bare name.
    if not bare or bare.startswith("${"):
        return True

    # 2 + 3. Bare name is a package we are generating in this run.
    if bare in generated_pkg_names:
        return True

    return False


def _group_is_valid(
    alternatives: list[str],
    generated_pkg_names: frozenset[str],
    oracle: AptOracle,
) -> bool:
    """Return True when at least one alternative in the group is acceptable.

    An alternative is acceptable when it is:
    * A debhelper substitution variable ('${...}').
    * A generated sibling package from this build (in *generated_pkg_names*).
    * A real apt package confirmed by *oracle*.
    """
    for alt in alternatives:
        if not alt or alt.startswith("${"):
            return True
        if alt in generated_pkg_names:
            return True
        if oracle.package_exists(alt):
            return True
    return False


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def validate_extra_depends(
    extra_depends: list[str],
    generated_pkg_names: frozenset[str],
    pkg_label: str = "",
    oracle: AptOracle | None = None,
) -> list[str]:
    """Validate one package's 'extra_depends' against the apt database.

    Passes through without querying apt:

    * Debhelper substitution variables ('${...}').
    * Dependencies whose bare name is in *generated_pkg_names* — these are
      sibling packages produced by this packaging run and are not in the apt
      database yet.  This covers both intra-package sibling pulls
      ('<app>-data (= ${binary:Version})') and dev-to-main lockstep pins
      ('<app> (= ${binary:Version})').

    All other entries are validated via *oracle*.  Entries that fail
    validation are dropped with an 'error:' log line.

    Args:
        extra_depends: The list of dep strings from 'pkg["extra_depends"]'.
        generated_pkg_names: Frozenset of all binary package names produced by
            '_build_package_layout' for this run.
        pkg_label: Human-readable label for the package (used in log messages).
        oracle: The apt oracle to use.  Defaults to
            :class:`~deb.resolution.oracle.HostAptOracle` (with a warning) if
            'None'.

    Returns:
        Filtered list in the same order as *extra_depends*.
    """
    if oracle is None:
        oracle = make_oracle(None)

    kept: list[str] = []
    dropped: list[str] = []

    for dep in extra_depends:
        if _is_generated_dep(dep, generated_pkg_names):
            kept.append(dep)
            continue
        if oracle.package_exists(dep):
            kept.append(dep)
        else:
            dropped.append(dep)

    if dropped:
        prefix = f"[{pkg_label}] " if pkg_label else ""
        for name in dropped:
            error(
                f"resolution-layer: {prefix}dropped '{name}' — not found in apt; "
                "not a valid Debian package name (upstream logical name?)"
            )

    return kept


def validate_build_depends_str(
    build_depends_str: str,
    oracle: AptOracle,
) -> str:
    """Validate and filter a Build-Depends string against an AptOracle.

    - Preserves debhelper/control syntax entries (e.g. debhelper-compat).
    - Preserves version constraints.
    - Attempts lib<name>-dev -> lib<name>-all-dev fallback.
    - Drops completely unresolvable entries.
    """
    if not build_depends_str.strip():
        return ""

    kept_groups: list[str] = []
    
    groups = [g.strip() for g in build_depends_str.split(",") if g.strip()]
    for group in groups:
        alternatives = [a.strip() for a in group.split("|") if a.strip()]
        
        valid_alternatives: list[str] = []
        for alt in alternatives:
            bare = alt.split("(")[0].strip()
            
            if not bare or bare.startswith("${") or bare in ("debhelper", "debhelper-compat"):
                valid_alternatives.append(alt)
                continue
                
            if oracle.package_exists(bare):
                valid_alternatives.append(alt)
                continue
                
            if bare.startswith("lib") and bare.endswith("-dev"):
                base_name = bare[3:-4]
                fallback_bare = f"lib{base_name}-all-dev"
                if oracle.package_exists(fallback_bare):
                    version_part = alt[len(bare):]
                    valid_alternatives.append(f"{fallback_bare}{version_part}")
                    continue
            
            error(f"resolution-layer: Build-Depends dropped '{bare}' — not found in {oracle.__class__.__name__}")

        if valid_alternatives:
            kept_groups.append(" | ".join(valid_alternatives))

    return ", ".join(kept_groups)


def resolve_runtime_dependencies(
    deps: list[str],
    oracle: AptOracle | None = None,
) -> list[str]:
    """Validate *deps* against the apt database; return only real packages.

    Algorithm
    ---------
    For each candidate dependency name:

    1. If it is a debhelper substitution variable ('${...}'), pass it through
       unconditionally — debhelper resolves these at build time and they are
       always valid in 'debian/control'.

    2. Query *oracle*.  If the package has a real candidate version, keep it.

    3. Otherwise, log a warning and drop it.  Dropping is safe because:

       * ELF runtime deps are already delegated to '${shlibs:Depends}'.
       * Any remaining dep that the oracle cannot locate is either a logical
         upstream name (e.g. 'libefl') or a stale/mistyped name — emitting
         it would only break installation on the target system.

    Args:
        deps: List of candidate package names as produced by
              '_non_elf_runtime_deps' in 'debian_generator'.
        oracle: The apt oracle to use.  Defaults to
            :class:`~deb.resolution.oracle.HostAptOracle` (with a warning) if
            'None'.

    Returns:
        Filtered list in the same order, containing only oracle-verified names.

    Logging
    -------
    * 'resolved: <name>'   — package confirmed by oracle.
    * 'dropped:  <name>'   — package not found; removed from Depends.
    """
    if oracle is None:
        oracle = make_oracle(None)

    resolved: list[str] = []
    dropped: list[str] = []

    for dep in deps:
        if oracle.package_exists(dep):
            resolved.append(dep)
        else:
            dropped.append(dep)

    if resolved:
        info("runtime-resolution: resolved deps: " + ", ".join(resolved))
    if dropped:
        for name in dropped:
            error(
                f"runtime-resolution: dropped '{name}' — not found in apt; "
                "not a valid Debian package name (upstream logical name?)"
            )

    return resolved


# ---------------------------------------------------------------------------
# Post-build artifact validation
# ---------------------------------------------------------------------------

def _dpkg_deb_field(deb_path: str, field: str) -> str:
    """Return the value of *field* from a .deb binary control block.

    Uses 'dpkg-deb -f' which reads the binary control file embedded in the
    archive without extracting it.  Returns an empty string on any error.
    """
    try:
        result = subprocess.run(
            ["dpkg-deb", "-f", deb_path, field],
            capture_output=True,
            text=True,
            timeout=15,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return ""
    return result.stdout.strip() if result.returncode == 0 else ""


def _parse_depends_field(depends: str) -> list[list[str]]:
    """Parse a Debian Depends field into a list of alternative groups.

    Each element in the returned list is a list of bare package names
    representing one OR-group (alternatives separated by '|').  Version
    constraints and architecture qualifiers are stripped so only the bare
    name remains for oracle validation.

    Example::

        "libc6 (>= 2.38), libefl (>= 1.26.99) | libother, python3"
        →  [["libc6"], ["libefl", "libother"], ["python3"]]

    Empty or whitespace-only fields return an empty list.
    """
    if not depends.strip():
        return []

    groups: list[list[str]] = []
    for group_str in depends.split(","):
        group_str = group_str.strip()
        if not group_str:
            continue
        alternatives: list[str] = []
        for alt in group_str.split("|"):
            bare = alt.strip().split("(")[0].strip()
            if bare:
                alternatives.append(bare)
        if alternatives:
            groups.append(alternatives)
    return groups


def validate_built_debs(
    deb_paths: list[str],
    generated_pkg_names: frozenset[str],
    oracle: AptOracle | None = None,
) -> None:
    """Inspect every .deb in *deb_paths* and fail if any Depends are invalid.

    This is the final artifact gate.  It catches dependency contamination
    that bypasses the pre-build 'debian/control' validation — most commonly
    upstream library names injected by 'dh_shlibdeps' through
    '${shlibs:Depends}' when the build host has non-Debian shlibs metadata.

    The oracle determines which apt database is authoritative:
    * :class:`~deb.resolution.oracle.ChrootAptOracle` — uses the target chroot's
      database; the correct choice when building in a Debian chroot.
    * :class:`~deb.resolution.oracle.HostAptOracle` — uses the host's database;
      may miss invalid deps that exist on the host but not in the target archive.

    Algorithm
    ---------
    For each .deb:

    1. Read the 'Package' and 'Depends' fields via 'dpkg-deb -f'.
    2. Parse 'Depends' into OR-groups (alternatives separated by '|').
    3. For each group, check whether at least one alternative is:
       - A debhelper substitution variable.
       - A generated sibling package (in *generated_pkg_names*).
       - A package the oracle confirms as installable.
    4. If any group has no valid alternative, collect the failure and
       enrich it with shlibs-repair diagnostics.

    Args:
        deb_paths: Absolute paths to the .deb files to validate.
            Non-.deb paths (e.g. .changes, .buildinfo) are silently skipped.
        generated_pkg_names: Frozenset of binary package names produced by
            this run.  Used to exempt sibling deps from oracle validation.
        oracle: The apt oracle to use.  Defaults to
            :class:`~deb.resolution.oracle.HostAptOracle` (with a warning) if
            'None'.

    Raises:
        RuntimeError: When one or more .deb files contain invalid dependencies.
    """
    if oracle is None:
        oracle = make_oracle(None)

    failures: list[str] = []

    for deb_path in deb_paths:
        if not deb_path.endswith(".deb"):
            continue

        pkg_name = _dpkg_deb_field(deb_path, "Package")
        depends_raw = _dpkg_deb_field(deb_path, "Depends")

        if not pkg_name:
            # Unreadable .deb — skip rather than abort; build failure is
            # already surfaced via dpkg-buildpackage's exit code.
            continue

        if not depends_raw:
            # No Depends field — nothing to validate.
            continue

        groups = _parse_depends_field(depends_raw)
        bad_groups: list[str] = []

        for alternatives in groups:
            if not _group_is_valid(alternatives, generated_pkg_names, oracle):
                bad_groups.append(" | ".join(alternatives))

        if bad_groups:
            # Collect bare names that failed for repair-diagnostic lookup.
            # A bad group may be "libefl | libother" — check each alternative.
            bad_bare: list[str] = []
            for grp in bad_groups:
                for alt in grp.split(" | "):
                    alt = alt.strip()
                    if alt and not alt.startswith("${") and alt not in bad_bare:
                        bad_bare.append(alt)

            repair_results = repair_shlibs_deps(bad_bare)
            repair_map = {r.bad_dep: r for r in repair_results}

            for bad in bad_groups:
                repair_lines: list[str] = []
                for alt in bad.split(" | "):
                    alt = alt.strip()
                    if alt in repair_map:
                        repair_lines.append(
                            repair_map[alt].format_diagnostic()
                        )

                failures.append(
                    f"  deb:     {deb_path}\n"
                    f"  package: {pkg_name}\n"
                    f"  invalid: {bad!r}\n"
                    f"  depends: {depends_raw}\n"
                    f"  oracle:  {oracle!r}\n"
                    f"  cause:   likely shlibs/substvars contamination "
                    f"(host has non-Debian library metadata)\n"
                    + ("\n".join(repair_lines) + "\n" if repair_lines else "")
                )

    if failures:
        lines = [
            "artifact dependency validation failed — built .deb(s) contain "
            "unresolvable dependencies:"
        ]
        for f in failures:
            lines.append("")
            lines.append(f.rstrip())
        raise RuntimeError("\n".join(lines))
